version: "3.8"

services:
  mysql:
    image: mysql:8.0.23
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis:7.2
    container_name: redis_local
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/Users/zranky/Workspace/redis/data
      - ./redis/conf/redis.conf:/Users/zranky/Workspace/redis/conf/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"